title: Your awesome title
email: your-email@domain.com
description:

source: './site-nl'
destination:  './public/nl'

baseurl: "/nl" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
asset_path: "https://d34j62pglfm3rr.cloudfront.net"

permalink: pretty

excerpt_separator: "<!--more-->"
# Build settings
markdown: kramdown

plugins:
- jekyll-feed


exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

collections:
  my_pages:
    output: true

  faqs:
    output: true
    permalink: /:collection/:path/
    title: FAQs
